---
title: "Spatial aggregation confounds null model-based inference of species association networks"
author: "Andrew J. Rominger"
format:
  pdf:
    keep-tex: true
    include-in-header: 
      text: |
        \usepackage{xr}
        \externaldocument{ab_supp}
        \newcommand{\sfig}[1]{Supplementary Figure~\ref{#1}}
        \newcommand{\ssec}[1]{Supplementary Section~\ref{#1}}
csl: mee.csl
bibliography: SpatAggNet.bib
---

## Abstract 




## Introduction


```{r}
#| label: setup
#| include: false

library(knitr)
library(dplyr)
library(ggplot2)

opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# helper function to load cache from supp
load_supp <- function(cname) {
    f <- sprintf("%s.*RData", cname) |> 
        grep(list.files("SpatAggNet_supp_cache/pdf", full.names = TRUE), 
              value = TRUE) |> 
        gsub("\\.RData", "", x = _)
    
    o <- lazyLoad(f, envir = globalenv())
    
    invisible(o)
}

```


```{r}
#| label: supp
#| include: false
#| cache: true
#| cache.extra: !expr file.info("SpatAggNet_supp.qmd")$mtime

# render the supplement so can be referenced and used in main

quarto::quarto_render("SpatAggNet_supp.qmd", quiet = FALSE)
```

```{r}
#| label: supp-tex-render
#| include: false

# need .aux file for corss referencing
tinytex::xelatex("SpatAggNet_supp.tex", clean = FALSE)
```


